### ISSUE TITLE
some cleanup

### ISSUE THREAD

**Issue by srigsby** [udp123/mono#1]
![screen shot 2018-02-05 at 3 30 01 pm](https://user-images.githubusercontent.com/1192684/35834250-b4d07668-0a89-11e8-91ac-d63da54bf25e.png)

add binaries and probably the /pkg folder to the .gitignore

**Comment by udp123** [comment]
added the easier of these two, `/pkg` now ignored and `/bin` should as well if not just all of `/go`. tried [this suggestion](https://stackoverflow.com/questions/5711120/gitignore-without-binary-files/25592735#25592735) to implement the ignore all without extensions but the quick v1 did not work so i reverted
